# try-catch combinator example
packages:
  plugin-combinator-1:
    actions:
      safeToDelete:
        kind: nodejs
        code: |
          function main(params) {
            if (params.delete)
              return {}
            throw new Error('Oh Crap')
          }

      delete:
        kind: nodejs
        code: |
          function main(params) {
            delete params[params.delete]
            return params
          }

      handleError:
        kind: nodejs
        code: |
          function main(params) {
            return {status: 'Um a very bad thing just happened - sorry?'}
          }

      trycatch:
        combinator: try safeToDelete catch handleError

      eca:
        combinator: if safeToDelete then delete

      forward:
        combinator: forward ["authkey"] after safeToDelete with ["delete"]
        inputs:
          authkey: very private
          delete: something

      retry:
        combinator: retry delete 5 times
